### ISSUE TITLE
Seq.duplicate doesn't allow to consume resulting duplicates in arbitrary order

### ISSUE THREAD

**Issue by johnmcclean-aol** [jOOQ/jOOL#103]
I have a fix for this issue, and will submit a PR soon (time allowing, I'm on vacation at the moment). The duplicate method picks one of the new Seqs as the leader and it always remains leader. This means that if a limit is applied to that leader, the other lagging Seq, can't continue beyond the limit, even if the original Seq has more data. As the limit has been applied, by the user, only to one of the two Seq's I think this is a bug. Here is a test to reproduce

    @Test
	public void testUnzipWithLimits() {
		
		Supplier<Seq<Tuple2<Integer, String>>> s = () -> Seq.of(
				tuple(1, "a"),tuple(2, "b"),tuple(3, "c"));

		Tuple2<Seq<Integer>, Seq<String>> u1 = Seq.unzip(s
				.get());

		assertTrue(u1.v1.limit(2).toList().containsAll(Arrays.asList(1, 2)));

		assertTrue(u1.v2.toList().containsAll(Arrays.asList("a", "b", "c")));

	}

We unzip a Seq, which uses duplicate, apply a limit to the first Seq we process and the second seq is missing data beyond that limit.

Congrats on 0.97, looks very cool :)

**Comment by lukaseder** [comment]
Thanks a lot for reporting. I can reproduce this with another unit test:

```java
Supplier<Tuple2<Seq<Integer>, Seq<Integer>>> reset = () -> Seq.of(1, 2, 3, 4, 5).duplicate();
Tuple2<Seq<Integer>, Seq<Integer>> duplicate;

duplicate = reset.get().map((s1, s2) -> tuple(s1.limit(2), s2.skip(2)));

assertEquals(asList(1, 2), duplicate.v1.toList());
assertEquals(asList(3, 4, 5), duplicate.v2.toList());
```

We'll keep this one as it doesn't have any additional potential side-effects, such as "unzip" implementations.
