### ISSUE TITLE
Add Seq.remove(T) and removeAll(T...), removeAll(Stream<T>), removeAll(Iterable<T>), removeAll(Seq<T>)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#110]
This will produce a new sequential stream, which no longer contains the first occurrence (`remove()`) or all occurrences (`removeAll()`) of the argument.

**Comment by stephenh** [comment]
Spiffy.

**Comment by lukaseder** [comment]
@stephenh : Let's see :) I wish I had the imagination to think of a less statefull, but equally elegant-looking algorithm. Strictly speaking, `Stream.filter()` operations must be stateless...
