### ISSUE TITLE
Add <K, A, D> Seq.grouped(Function<? super T, ? extends K> classifier, Collector<? super T, A, D> downstream)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#119]
Similar to #105, #117, we should offer a grouping operation that collects stream elements into groups lazily, but eagerly collects each group's values

**Comment by tkroman** [comment]
I wonder if it would be more efficient to move the `downstream` one level lower (into the `grouped`) implementation?
Anyway, LGTM. 
Also, moving the collector into the implementation seems like another way to introduce bugs, so I withdraw that proposal.

**Comment by lukaseder** [comment]
I had thought of this, indeed. We could reverse dependencies such that the "simple" `grouped()` call would just be collecting "downstream" into a `Seq`.

I'll think about it. Perhaps there's a low hanging fruit.
