### ISSUE TITLE
SQL.ResultSetIterator.hasNext should not close result sets

### ISSUE THREAD

**Issue by irobertson** [jOOQ/jOOL#129]
SQL.ResultSetIterator will call close on its resultSet if the resultSet's next() method returns false. There are a few problems with this:
* This contradicts the documentation, which states that it is the client's responsibility to close the resultSet.
* It prevents the caller from calling, for example, previous(), after using a ResultSetIterator.
* It can cause developers to believe that they in fact do not need to close the ResultSet after using a ResultSet in a stream; this assumption can be violated if the stream is terminated early, e.g. via findFirst().

Changing behavior at this point is likely to break some existing code written under the false assupmtion listed above; if this is bug is addressed, it will be necessary to call it out in the change log.

**Comment by lukaseder** [comment]
Thanks for your suggestion Ian. You're absolutely right. The solution is:

- Not to close the `ResultSet`
- Let `ResultSetIterator` implement `AutoCloseable`
- Let the `SQL.seq()` register an `onClose(() -> it.close())` hook

I've noticed similar things in the context of jOOQ. Java 8's `Stream` doesn't work very well with `AutoCloseable` resources.
