### ISSUE TITLE
Add Seq.mapBy or toMap

### ISSUE THREAD

**Issue by stephenh** [jOOQ/jOOL#132]
I'm currently writing something like:

```
Seq.toMap(Seq.of(FooEnum.values()).map(f -> tuple(f, createValue(f))));
```

And thinking basically what I want is to take a Seq of keys, provide a value function, and get a map of each key + the result of applying the function, e.g.:

```
Seq.of(FooEnum.values()).mapBy(f -> createValue(f));
```

I was wondering instead of "mapBy" maybe "toMap":

```
Seq.of(FooEnum.values()).toMap(f -> createValue(f));
```

But there is already the static Seq.toMap, so not sure if that'd work in terms of overloading. But, either way, I'm also not tied to the proposed "mapBy" method name. Or "mapTo". Something like that.

**Comment by lukaseder** [comment]
Thank you very much for your suggestions. There's already a `toMap(keyMapper, valueMapper)` method:

```java
<K, V> Map<K, V> toMap(Function<? super T, ? extends K> keyMapper, Function<? super T, ? extends V> valueMapper);
```

You could use it in your case:

```java
Seq.of(FooEnum.values()).toMap(k -> k, v -> createValue(v));
```

I understand that the `k -> k` identity function is a bit tedious, but we cannot overload `toMap()` with a version that only maps values, but not keys. Someone else might prefer an overload of `toMap()` that only maps keys, not values. Alternatively, we could name these two methods `toMapByKey()` and `toMapByValue()`, but then we're not really adding value compared to the existing version that takes two functions.

Hence: I think we have all we need in the existing API right now...?

**Comment by stephenh** [comment]
Ah, okay, I had seen that toMap overload but thought it was static. I agree, that looks good; I'll use that instead. Thanks!

**Comment by lukaseder** [comment]
OK, thanks for the feedback
