### ISSUE TITLE
Unchecked.function() with recovery

### ISSUE THREAD

**Issue by jrglee** [jOOQ/jOOL#135]
I love the idea of wrapping a legacy function and be able to ignore the exception or re-wrap it as a `RuntimeException`. Sometimes there is a case of a default or fallback value if the function itself crashes, e.g.: parsing. For this situation it would great to have something like:

```java
public static <T, R> Function<T, R> function(CheckedFunction<T, R> function, Function<Throwable, R> handler)
```
or
```java
public static <T, R> Function<T, Optional<R>> function(CheckedFunction<T, R> function, Consumer<Throwable> handler)
```

In this case the handler is only for logging purposes since the return would be `empty()`.

Thoughts?

**Comment by lukaseder** [comment]
That's a neat idea. We actually do this in our jOOQ integration tests. Haven't thought about standardising on this API in jOOλ yet. I like both suggestions. As `Function` and `Consumer` are "lambda-overloadable", we can add both

**Comment by lukaseder** [comment]
I jumped too quickly :-/ We already have the `Consumer` variant, and it behaves differently from what you've described here (it must re-throw a runtime exception).

**Comment by danieldietrich** [comment]
Interesting idea. I like to directly work with the result, regardless if an error occurred or not. It is a better style of programming to work with values. A handler can only produce a side-effect, which adds additional complexity to your application because a computation may modify several places. Working with values, you have to look only at one place.

Scala uses the `Try` monad for this purpose: http://danielwestheide.com/blog/2012/12/26/the-neophytes-guide-to-scala-part-6-error-handling-with-try.html

**Comment by jrglee** [comment]
The first example is inspired in the `Future.recoverWith` from Scala. The second example won't even compile because the name and argument list already define a method with a different return type. I am looking for something like Scala's `lift()`, e.g.:

```java
public static <T, R> CheckedFunction<T, Optional<R>> lift(Function<T, R> function)
````
the usage is something like this

```java
Unchecked.function(Unchecked.lift(this::dangerousFunction)).apply(value).ifPresent(this::consume)
```
I know this adds complexity, I still prefer my original idea :smile_cat:

**Comment by danieldietrich** [comment]
Isn't `lift` more like this?

```java
public static <T, R> CheckedFunction<T, Optional<R>> lift(CheckedFunction<T, R> function) {
    return function;
}

Function<T, R> f = ...

// and then
lift(f::apply)

// or
lift(t -> r);
```

**Comment by jrglee** [comment]
@danieldietrich Thanks for correcting my example, `lift()` is already sufficient but it leaves no option for me to inspect and log the exception. This is why I suggested some way to use `Unchecked.function` in a way I can consume the exception for logging and get an optional back.

I see you already implemented it in javaslang, pretty cool!

**Comment by danieldietrich** [comment]
@jrglee thx :)

**Comment by lukaseder** [comment]
I've marked this as won't fix. There is limited evidence that this new API would really add enough value compared to the added API complexity. Besides, the standard way of handling such use-cases would be:

- To use `try { }  catch { }` (they're not evil)
- To use a `Try` monad, if you must
