### ISSUE TITLE
tracking 269

### ISSUE THREAD

**Issue by hepin1989** [jOOQ/jOOL#136]
http://openjdk.java.net/jeps/269

**Comment by lukaseder** [comment]
Thanks for the info. I'm aware of that JEP. What's the relevance for jOOλ, in your opinion?

**Comment by hepin1989** [comment]
@lukaseder I means you could add make some commit to it:).

**Comment by lukaseder** [comment]
I'm sorry @hepin1989, but I really don't know what you're trying to tell me with this issue...
