### ISSUE TITLE
Add limitUntilClosed(), limitWhileClosed(), skipUntilClosed(), skipWhileClosed()

### ISSUE THREAD

**Issue by irobertson** [jOOQ/jOOL#141]
limitUntil(Predicate) is useful, but in some cases, one wants the list up to and including a matching element, as opposed to limitUntil's behavior of excluding the matching element.

limitUntilAfter is one possible method name; another is limitUntilClosed. I'm not sure whether it makes sense to have a corresponding version of limitWhile, but if it does, the name of limitUntilClosed would have a nicely matching limitWhileClosed name.

**Comment by lukaseder** [comment]
Interesting thought, thanks for suggesting. I can certainly see the use-case, but I haven't seen this kind of method in other libraries, e.g. in Scala's collections.

How would FP-aficionados do this? Perhaps there's another idiom...?

**Comment by danieldietrich** [comment]
Maybe this could be accomplished with a foldRight that acts lazily. This allows us to shortcut/break the loop on an individual condition.

**Comment by danieldietrich** [comment]
More information [here](https://github.com/javaslang/javaslang/issues/779). Follow the links!

**Comment by irobertson** [comment]
I'm not sure if I follow. The closest I cold come up with is:

        ArrayList<String> reduce = Stream.of("bob", "joe", "sue", "jack",
"sam")
            .reduce(
                new Tuple2<>(new ArrayList<String>(), true),
                (tuple, name) -> {
                    if (tuple.v2()) {
                        tuple.v1().add(name);
                        return new Tuple2<>(tuple.v1(),
!"sue".equals(name));
                    }
                    else {
                        return tuple;
                    }
                },
                (x,y) -> { throw new RuntimeException(); })
            .v1(); // returns ["bob", "joe", "sue"]

If the referenced bug were fixed, then this would not have to (cheaply)
stream through the remainder of the list.

One downside is that we end up creating a list, rather than a stream,
which, even if the referenced bug is fixed, still leaves us with a non-lazy
situation.

It seems that to do this properly with Streams, one needs something like a
stateful predicate.

  - Ian

**Comment by danieldietrich** [comment]
Yes, I also think when using Java's Stream in this context s.th. like a stateful predicate is needed.

limitUntilClosed could be expressed by a skipRightUntil but this makes no sense with a possible infinite Stream of elements.

**Comment by irobertson** [comment]
I haven't been able to find much from the FP world on this. Notably, in
http://voidmainargs.blogspot.de/2011/08/folding-stream-with-scala.html they
show how to use scalaz's lazy foldRight to emulate the break construct in
for loops, but it does not appear to be related to more general concepts.

Notably, there is are similar requests for RxJava (
https://github.com/ReactiveX/RxJava/issues/1649) and Ceylon (
https://github.com/ceylon/ceylon.language/issues/739). The RxJava folks may
have it right, that this is too specialized to justify adding to a general
purpose library.

  - Ian

**Comment by lukaseder** [comment]
What I generally don't like about the current suggestion is that it uses a common concept (windowing) and maps it to a method name, rather than implementing the whole concept.

In SQL, you'd be using the `LEAD()` and `LAG()` window functions to access the next/previous row in iteration order. Window functions are rather difficult to implement in FP, as they need to be able to buffer the outer stream before it is consumed.

One idea that rudimentarily implements windowing in Scala is the `IterableLike.sliding()` method, which gives access to a fixed number of elements before the current element in iteration order (no partitioning or reordering, and no look aheads). But it might be sufficient to implement the requirement of a `limitUntilAfter()`:

```java
Seq.seq(...) // Seq<E>
   .sliding(1) // Seq<Tuple2<E, Seq<E>>
   .limitUntil(tuple -> tuple.v2.findFirst().map(predicate).orElse(false))
   .map(tuple -> tuple.v1);
```

**Comment by lukaseder** [comment]
Heck. I just needed this myself today. And there's also `range()` and `rangeClosed()`, which is inspired by `IntStream.range()` and `rangeClosed()`. Let's do this!

**Comment by lukaseder** [comment]
This will be easier to implement using `Spliterator` rather than `Iterator` as things were implemented until now. See also #144
