### ISSUE TITLE
SeqImpl constructor taking in stream should ensure stream is sequential.

### ISSUE THREAD

**Issue by irobertson** [jOOQ/jOOL#147]
Because Seq relies on being sequential, and always returns false for isParallel, it should assign this.stream to stream.sequential(), or throw an IllegalArgumentException if stream.isParallel returns true.

All additional methods in Seq are implemented by converting the stream to an iterator, meaning that in practice, the current implementation is not likely to cause problems in most cases. However, it is not inconceivable that a method taking a stream might take certain actions only if the stream is sequential, and if passed a SeqImpl constructed from a parallel stream, could produce unexpected results.

**Comment by lukaseder** [comment]
I agree that we should handle this. I think it is OK for a stream source to be parallel at some point. E.g.

```java
Stream<T> stream = 
Stream.of(...)
      .parallel()
      .map(t -> ...)
      .filter(t -> ...);

// Implicitly sequential():
Seq.seq(stream)
   .zipWithIndex()
   .forEach(System.out::println);
```

At the point when `stream` gets wrapped by `Seq`, the pipeline should become sequential again as of your suggestion 1), assigning this.stream to stream.sequential()
