### ISSUE TITLE
Add Seq.take / drop as aliases for limit / skip

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#170]
The JDK 9 will add new `takeWhile()` and `dropWhile()` methods to `Stream`. For completeness and consistency sake, jOOλ should provide aliases as well.

----
See also:
- http://stackoverflow.com/a/32304570/521799
- http://download.java.net/jdk9/docs/api/java/util/stream/Stream.html

**Comment by patrox** [comment]
Do I understand correctly, that you would like to add sth like:

```java
default Seq<T> take(int n) {
    return limit(n);
}

default Seq<T> drop(int n) {
    return skip(n);
}
```

**Comment by lukaseder** [comment]
Yes

**Comment by patrox** [comment]
Then I would like to contribute: https://github.com/jOOQ/jOOL/pull/196

**Comment by lukaseder** [comment]
Wonderful, thank you very much!
