### ISSUE TITLE
Add Seq.findFirst(Predicate)

### ISSUE THREAD

**Issue by michel-kraemer** [jOOQ/jOOL#173]
I'm looking for a short way to find a single element in a stream. I know you can do `filter(Predicate).findFirst()` but this was not obvious to me first. After reading #93 I wonder if it would be worth adding a `find(Predicate)` or maybe `findFirst(Predicate)` method. What do you think?

I really love this library by the way :)

Cheers,
Michel

**Comment by lukaseder** [comment]
Thanks for your nice words, and for your suggestion.

I agree that this deserves some additional convenience. Scala's `TraversableLike` has such a method:

```scala
  def find(p: A => Boolean): Option[A] = {
    var result: Option[A] = None
    breakable {
      for (x <- this)
        if (p(x)) { result = Some(x); break }
    }
    result
  }
```

In Java Streams, the difference between `findFirst()` and `findAny()` is relevant in the context of ordered or unordered streams, so I prefer to re-use the existing terminology. As `Seq` is an ordered, sequential stream, `findFirst(Predicate)` is a good choice.
