### ISSUE TITLE
Issue with Collect method override in Collectable

### ISSUE THREAD

**Issue by johnmcclean-aol** [jOOQ/jOOL#184]
In jool 0.9.9 - See screen grab from Eclipse - the error message is 

      "The method collect(Collector<Object,capture#1-of ?,List<Object>>) is undefined for the type Seq<String>"

I'm not sure if this only happens in Eclipse or more generally, I think it is worth fixing either way (should be fixable by moving the default collect implementations into Seq).

<img width="522" alt="screen shot 2016-01-14 at 5 00 51 pm" src="https://cloud.githubusercontent.com/assets/9964792/12331223/8caaeee8-bae0-11e5-85c3-1bbeb6c626ca.png">

Eclipse build info 

Eclipse IDE for Java Developers

Version: Luna Service Release 2 (4.4.2)
Build id: 20150219-0600

**Comment by lukaseder** [comment]
I'm suspecting an Eclipse bug here. There had been tons of these in recent releases. I suggest upgrading to Eclipse 4.5.1
