### ISSUE TITLE
Apply co and contravariance on Tuple.map(Function[N]) calls

### ISSUE THREAD

**Issue by danieldietrich** [jOOQ/jOOL#185]
Hi Lukas,

I recognized that the Function arguments of the Tuple*.map methods don't have generic bounds. Currently I have no concrete use case where this fails to work but I ask myself why it is intended to be like this.

Example (Tuple2):

```java
public final <R> R map(Function2<T1, T2, R> function) { ... }

public final <U1> Tuple2<U1, T2> map1(Function1<? super T1, ? extends U1> function) { ... }
```

I also think for the result type R of the map arg Function2 no bound is needed. Does this apply also for T1 and T2 here?

If yes, why T1 needs to be bounded then in map1?

I thought I understood generics in Java. But since yesterday I'm not sure I get the corner cases...

Greets

Daniel

**Comment by lukaseder** [comment]
Thanks for the hint. This is an oversight, and shouldn't be this way. The usual rules about co and contravariance apply, regardless the number of function arguments. The method signature should be:

```java
public final <R> R map(Function2<? super T1, ? super T2, ? extends R> function) { ... }
```

**Comment by danieldietrich** [comment]
Ok, thank you!
