### ISSUE TITLE
Add Element Accessor Interfaces to Tuples

### ISSUE THREAD

**Issue by jmax01** [jOOQ/jOOL#197]
It would be helpful if Tuples implemented element accessor interfaces.

```java
public interface V1<T1>{
    T1 v1();
}
public interface V2<T2>{
    T2 v2();
}
public interface V3<T3>{
    T3 v3();
}
public class Tuple1<T1> implements Tuple, V1<T1>, Comparable<Tuple1<T1>>, Serializable, Cloneable { ... }

public class Tuple2<T1,T2> implements public class Tuple2<T1, T2> implements Tuple, V1<T1>, V2<T2>, Comparable<Tuple2<T1, T2>>, Serializable, Cloneable { ..}

public class Tuple3<T1,T2,T3> implements public class Tuple3<T1, T2,T3> implements Tuple, V1<T1>, V2<T2>, V3<T3>, Comparable<Tuple3<T1, T2,T3>>, Serializable, Cloneable { ..}
```

The use cases are many, a simple one is shown below:

```java
public class ElementAccessorInterfacesTest {
    
    @Test
    public void elementAccessorInterfaceExample() {

        Tuple2<Long, String> t2 = Tuples.tuple(2L, "t2");

        Tuple3<Long, String, String> t3 = Tuples.tuple(3L, "t3", "");

        List<String> concatenated = Stream.of(t2, t3)
            .map(ElementAccessorInterfacesTest::concat)
            .collect(Collectors.toList());

        assertEquals("2t2", concatenated.get(0));
        assertEquals("3t3", concatenated.get(1));

    }

    public static final <T extends Tuple & V1<Long> & V2<String>> String concat(T t) {
        return t.v1() + t.v2();
    }
}
```

**Comment by lukaseder** [comment]
Thanks for your suggestion. I'm a bit reluctant to go ahead with this. The rationale is explained here:
http://blog.jooq.org/2015/10/22/the-danger-of-subtype-polymorphism-applied-to-tuples

Effectively, the `v2` in `Tuple3` has absolutely nothing to do with the `v2` in `Tuple5`.

Perhaps, I'm missing something, though. What is a real-world use-case for going with such intersection types?

**Comment by lukaseder** [comment]
Perhaps a second opinion would be interesting. What's your take on this, @danieldietrich? Your tuples don't expose common per-attribute super types either...

**Comment by danieldietrich** [comment]
I've seen this issue when it was created and thought about it. In my applications tuples are bound to a specific context. Typically I know exactly the tuple I deal with.

Adding element accessors adds an additional dimension of abstraction. We broaden the domain of problems we are able to model using tuples. Personally I prefer keeping things simple. When in doubt I do not add additional functionality.

Tuples are relatively simple building blocks. They represent indexed data. The benefit with the suggested approach over indexed sequences is that we can't get an IndexOutOfBoundsException. When it compiles we know that the indices are correct.

It reminds me a little bit of my first object oriented program (written in Java 1.2). I came from Pascal and did not know how to model the assignment. I ended up with a program where literally everything was a class. Here I also have the feeling that we don't need this extra layer of abstraction.

Hope this helps.

\- Daniel

**Comment by lukaseder** [comment]
Thanks very much for your comment, @danieldietrich. I suspect that your point goes well with removing recursive generics from type hierarchies again :)

**Comment by lukaseder** [comment]
I'm closing this as "won't fix". If in your application design there is really a strong tie between attribute indexes among `(a1, a2)` and `(b1, b2, b3)`, you have a variety of options to work around the perceived lack of functionality:

1. Use `Tuple3` only, and make the third value `Optional<?>` (or `null`). That would probably be the cleanest solution - similar to SQL.
2. Use arrays or collections. In this case, you'll lose the per-attribute type safety, but the variable arity is not unexpected
3. Use class hierarchies, where you'll replace `Tuple2` by `A` and `Tuple3` by `B extends A`. While this behaviour is unexpected in tuples, it may make perfect sense in your domain.

**Comment by danieldietrich** [comment]
> I suspect that your point goes well with removing recursive generics from type hierarchies again :)

Yep :)
