### ISSUE TITLE
Add <T> Seq<T> seq(Enumeration<T> enumeration)

### ISSUE THREAD

**Issue by sargue** [jOOQ/jOOL#205]
```java
interface Seq {
    /**
     * Wrap an <code>Enumeration</code> into a <code>Seq</code>.
     */
    static <T> Seq<T> seq(Enumeration<T> enumeration) { ... }
}
```

What do you think about this? It should work like the Iterator wrapper (probably with some more boilerplate code as I think there is no standard Spliterator for Enumerations).

**Comment by sargue** [comment]
Possible implementation?

```java
static <T> Seq<T> seq(Enumeration<T> enumeration) {
    Spliterator<T> spliterator = Spliterators.spliteratorUnknownSize(new Iterator<T>() {
        @Override
        public boolean hasNext() {
            return enumeration.hasMoreElements();
        }

        @Override
        public T next() {
            return enumeration.nextElement();
        }
    }, ORDERED);
    return Seq.seq(spliterator);
}
```

**Comment by lukaseder** [comment]
Nice thinking. This would certainly help working with legacy APIs like `Vector` or `Properties`. Did you have any other specific use-case in mind?

Would you be interested to provide this as a pull request?

**Comment by sargue** [comment]
Yeah, mostly legacy APIs. I can't think of another use. I've found myself using it with the Servlet API `HttpServletRequest.getParameterNames()` for example.

I will prepare and send a PR.

**Comment by lukaseder** [comment]
Ah, true. Servlets also use this type, still. Thanks, looking forward!

**Comment by lukaseder** [comment]
Oh, btw, I think you can skip the `Spliterator` and pass the `Iterator` directly to `seq()`
