### ISSUE TITLE
Alias Seq.of() methods with Seq.seq()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#211]
The JDK `Stream.of()` convention has been taken over in `Seq` for convenience. But the choice of `of()` as a method name is not the best of designs, as it prevents static imports in client code, in case of which we want to be able to simply write things like `seq(1, 2, 3)`, rather than `Seq.of(1, 2, 3)`

**Comment by amaembo** [comment]
Actually I liked somehow such difference in your library, so I don't like this fix :-) Having dedicated name `of(elements...)` and tons of convenient overloads with different name (like `seq(Stream)`, `seq(Collection)`, etc.) reduces the confusion. What if you want to create `Seq` of single element, but this element is actually a `Collection`? Actually this change might even break the existing code making it non-compilable! I doubt that adding such confusion worth potential shortening of the code size by three chars (`Seq.of` -> `seq`).

Compare to Guava [`ImmutableList`](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/collect/ImmutableList.html): `of(elements)`, but `copyOf(Iterable)`.

In my library most of factory methods are named `of`, but if I could start the library again, I would use `from` for everything except explicit element lists. I actually had problems when I wanted to create one-element `StreamEx<Collection<XYZ>>`.

**Comment by lukaseder** [comment]
Hmm, how can the new methods break anything existing? The existing methods are always more specific than the new ones...

Apart from the above risk, style and naming is always a matter of taste. I just kept forgetting that there were two "special" `Seq` constructors for individual and varargs elements, and that started pissing me off :) And yes. I would totally prefer if JDK 9 had added `Map.map()`, `List.list()`, and `Set.set()`, but oh well.

**Comment by amaembo** [comment]
Well, probably I was wrong about breaking the existing code. The problem would arise if you add `Seq.of(Iterable)` instead of `Seq.seq(elements...)`.

**Comment by lukaseder** [comment]
Oh yes, you're right. It's a one-way street. No new `of()` methods can be added. Hmm, this means, though, that after this fix, no new `seq()` methods can be added either. :-/

I guess I'll revert, then. Thanks for the input!
