### ISSUE TITLE
Add Consumer1 to Consumer16

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#215]

**Comment by amaembo** [comment]
Should `Consumer0` provide `static Consumer0 from(Runnable r)` method?

Also, IIRC what you are calling `curry` is actually called `bind` or "partial application" in FP. Curry operation creates higher-order function. Instead of 

    default Consumer0 curry(T1 v1) {
        return () -> accept(v1);
    }

It should be like

    default Function<T1, Consumer0> curry() {
        return () -> v1 -> accept(v1);
    }

[Further reading](https://en.wikipedia.org/wiki/Currying#Contrast_with_partial_function_application).

**Comment by lukaseder** [comment]
Thanks for the hint. It should also extend `Runnable`. I had thought about this, but then forgotten.

Hmm, the curry hint is interesting. I've seen `curried()` (e.g. in Scala) to return these kinds of functions. Indeed, perhaps `partiallyApply()` might be a better term. Will think abou this. Existing `Function[N]` API already has `curry()`, too, so this should be discussed in a separate issue, where things might be fixed.

**Comment by lukens** [comment]
It would be good to have Predicate1 to 16 too, although these can be partially mimicked with functions that return booleans.

**Comment by lukaseder** [comment]
I'm not a fan of adding those. Boxing `boolean` is cheap (unlike `Integer` or `Long`):

```java
    public static Boolean valueOf(boolean b) {
        return (b ? TRUE : FALSE);
    }
```

So, a `Predicate3<T1, T2, T3>` is just a `Function3<T1, T2, T3, Boolean>`. [In my personal opinion](http://blog.jooq.org/2014/04/04/java-8-friday-the-dark-side-of-java-8), a lot of these interfaces were added to the JDK prematurely and are rendered obsolete (hopefully) by project Valhalla.

Most other languages and their libraries only have `Function[N]` and `Action[N]` types, the latter being unnecessary if there is a `Unit` type, in case of which a "unit function" will suffice.

**Comment by lukaseder** [comment]
(of course, if you can show me a compelling use-case, I might be convinced otherwise)

**Comment by lukens** [comment]
I doubt I can, it was mainly suggested for completeness in mirroring the Java classes. I guess the `and()`, `or()` and `negate()` methods or predicates might be useful, but I've never used them personally (well, except for my one use of `negate()` in my `not()` method - which I've just noticed you also beat me to the punch on).

**Comment by lukaseder** [comment]
True, those methods might come in handy in edge cases, where the left-hand side of the operator is not a lambda expression. But as you've noticed, the static methods work just the same.

If these types were added for completeness' sake, we'd probably need tons of types of the form `ToIntFunction[N]`, `ToLongFunction[N]`, `ToDoubleFunction[N]`, and perhaps even `LongToIntFunction[N]` for those cases where 5 primitive long arguments are mapped to an `int`. As you can see... :-)
