### ISSUE TITLE
Output is incorrect for foldLeft examples

### ISSUE THREAD

**Issue by jlorenzen** [jOOQ/jOOL#227]
The `foldLeft` example outputs in the `README.md` seems to be incorrect. I'm using jOOL version `0.9.10`.

When I run `Seq.of("a", "b", "c").foldLeft("", (u, t) -> t + u)` I get `cba` and not `abc`.
When I run `Seq.of("a", "b", "c").foldRight("", (t, u) -> t + u)` I get `abc` and not `cba`.

Not sure if this is a bug or just incorrect documentation but thought you should know.

**Comment by lukaseder** [comment]
Thanks for the hint. Indeed, the readme was wrong. Fixed
