### ISSUE TITLE
Unchecked.THROWABLE_TO_RUNTIME_EXCEPTION should reset interrupt flag, if wrapping an InterruptedException

### ISSUE THREAD

**Issue by stephenh** [jOOQ/jOOL#230]
I'm writing some code that deals with InterruptedExceptions, and AFAIU instead of just doing:

```
try {
  something();
} catch (InterruptedException e) {
  throw new RuntimeException(e);
}
```

The preferrable pattern is:

```
try {
  something();
} catch (InterruptedException e) {
  Thread.currentThread().interrupt();
  throw new RuntimeException(e);
}
```

Given that, I was thinking this would be a useful addition to Unchecked.java:

```
    public static final Consumer<Throwable> THROWABLE_TO_RUNTIME_EXCEPTION = t -> {
        if (t instanceof InterruptedException)
            Thread.currentThread().interrupt();

        if (t instanceof Error)
            throw (Error) t;

        if (t instanceof RuntimeException)
            throw (RuntimeException) t;

        throw new UncheckedException(t);
    };
```

As then I could use the various Unchecked functions to get around the ugly catch/rethrow + also get interrupt reset.

Seem reasonable?

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I personally think that this improvement is much too specific for the generic default that is placed in `THROWABLE_TO_RUNTIME_EXCEPTION`. Also, it might be rather unexpected to someone who does use multithreading code with jOOλ.

> AFAIU instead of just doing [...] The preferrable pattern is

Can you provide some sources?

**Comment by stephenh** [comment]
> Can you provide some sources?

Sure:

http://www.ibm.com/developerworks/library/j-jtp05236/

> Also, it might be rather unexpected to someone who does use
> multithreading code with jOOλ

Yeah. FWIW, I had originally started down the track of writing my own "catch and reset" util methods, e.g.:

```
  @FunctionalInterface
  public interface InterruptedRunnable {
    void run() throws InterruptedException;
  }

  public static void handleInterrupt(InterruptedRunnable r) {
    try {
      r.run();
    } catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new RuntimeException(e);
    }
  }
```

But then needed one for supplier, and consumer, which is when I started thinking this was going to get tedious, and it'd be nice to just use all of the existing Unchecked methods.

That said, after re-reading that article, I'm still tempted to think that adding this to THROWABLE_TO_RUNTIME_EXCEPTION not only should not surprise anyone, but if anything is actually the correct thing to do, and that it currently suppressing InterruptedException (well, converting to a different exception) without resetting the interrupt bit could be considered a bug.

What do you think?

**Comment by stephenh** [comment]
Have you heard of sneaky throws? What do you think about using that in THROWABLE_TO_RUNTIME_EXCEPTION to avoid having to wrap the original exception in a runtime exception?

http://stackoverflow.com/questions/14038649/java-sneakythrow-of-exceptions-type-erasure

(Using sneaky throws is somewhat orthogonal to InterruptedException handling, but also somewhat related given it could avoid converting the exception type.)

I have not fully thought throw it, but it seems cute.

**Comment by lukaseder** [comment]
> Sure:
> 
> http://www.ibm.com/developerworks/library/j-jtp05236/

Ugh, I was afraid that an authority like Brian Goetz would have already confirmed that :) Thanks for the link. Nice read.

> but if anything is actually the correct thing to do, and that it currently suppressing InterruptedException (well, converting to a different exception) without resetting the interrupt bit could be considered a bug.

Hmm, the point of the current implementation is not to *suppress* any exception, but to make sure it is no longer a checked exception. You should still handle it somewhere. In fact, you should catch `UncheckedException` and unwrap its cause to deal with it, unless it's a fatal error.

The "ideal" solution here (without having thought this through) would be to add a compiler flag that "unchecks" all existing checked exceptions. Another solution is...

> Have you heard of sneaky throws?

... yes of course. See `SeqUtils.sneakyThrow()`. The `RETHROW_ALL` consumer does precisely that. It is a dangerous practice. You usually cannot catch a checked exception (except for `Exception` and `Throwable`, which are `RuntimeException` supertypes) that is not explicitly declared as being thrown by some method in the `try` block. Which means, you cannot properly deal with the `InterruptedException` either.

One more thought: If we do deal with this particular exception specifically, what happens to all the other "important" checked exceptions, which would currently be hiding a bug? We'll never get done :)

On the other hand, there's the `org.jooq.lambda.Blocking` type, which creates "blocking" versions of the different functional interfaces (e.g. for use with `Stream.parallel()` or the fork join pool). I could definitely see handling this case in there.

**Comment by stephenh** [comment]
> Brian Goetz

Ha, nice, I actually missed that he was the author of that article.

> The "ideal" solution here (without having thought this through) would be to
> add a compiler flag that "unchecks" all existing checked exceptions.

Hehe. My team's chat room log from ~2 weeks ago:

```
[8:57 PM] Stephen Haberman it would be great if java 9 just got rid of checked exceptions
[8:57 PM] Stephen Haberman maybe as a compiler flag.
```

So, fair enough, maybe I can go submit an issue/PR against the OpenJDK codebase. :-)

> The RETHROW_ALL consumer does precisely that

Ah nice, I had not seen that. Yeah, agreed about sneakyThrows, sorry for the tangent on that.

> One more thought: If we do deal with this particular exception specifically,
> what happens to all the other "important" checked exceptions

Good to think of that, but AFAIK the InterruptedException is the only surprise/gotcha of "btw, you have to do special things when you catch this exception". So I don't think this is very likely to become a slippery slope.

So I think it's still a good idea, but of course open for more discussion/your final decision.

**Comment by lukaseder** [comment]
OK, I did some more research and found a lot of application of your suggested pattern in Guava. I'm convinced now. Thanks again, very nice finding!

**Comment by stephenh** [comment]
Great, thanks!
