### ISSUE TITLE
Add 'Release' section to wiki

### ISSUE THREAD

**Issue by tkroman** [jOOQ/jOOL#233]
Seeing as JOOL releases rather frequently and even minor versions often bring something new to API or enhancements to the existing methods, it would be nice to have a summary section for each (minor) release in wiki. I have something like this in mind: https://github.com/neo4j/neo4j/wiki/Changelog
WDYT?

**Comment by lukaseder** [comment]
Hmm, I currently wouldn't want to maintain a separate wiki for the library. Everything is already documented using GitHub's milestones: https://github.com/jOOQ/jOOL/milestones?state=closed

Does that fit your needs?

**Comment by tkroman** [comment]
Oh, didn't notice that button. Yep, that totally fits. Thanks!
