### ISSUE TITLE
Add "Optional<T> findLast()" method to "Seq<T>"

### ISSUE THREAD

**Issue by tlinkowski** [jOOQ/jOOL#241]
Currently, getting the last element from a `Seq` is possible by calling `seq.reverse().findFirst()` but:

1. it entails unnecessary collecting to a list
2. it is less readable than `seq.findLast()`

`Seq.findLast` would do exactly what `Iterators.getLast` does in Guava.

Optionally, as a generalization we could also have methods `limitEnd(int maxSize)` and `skipEnd(int n)`. They could be implemented with a circular buffer of size `maxSize/n` (e.g. an `ArrayDeque` could be used for this purpose). I guess it'd get harder if we wanted to have `long`s instead of `int`s as the arguments.

**Comment by amaembo** [comment]
Note that `findLast` is an equivalent to `reduce((a, b) -> b)` (which perfectly works even with normal Java streams w/o jOOL and even with parallel streams).

**Comment by lukaseder** [comment]
Nice idea, thanks for the implementation hint, @amaembo. Much appreciated! I'm still in favour of adding `findLast()` for readability purposes. Otherwise, `findFirst()` wouldn't be necessary either, as it could be written with `reduce((a, b) -> a)`

**Comment by lukaseder** [comment]
(Just realised how dumb my suggestion was ;), performance-wise )
