### ISSUE TITLE
Add Seq.indexOf method(s)

### ISSUE THREAD

**Issue by tlinkowski** [jOOQ/jOOL#242]
Since we have `Seq.contains` and `Seq.get(index)`, it'd be nice to also have `long indexOf(T item)` or `OptionalLong indexOf(T item)`.

Incidentally, we could also have `long/OptionalLong indexOf(Predicate<? super T> predicate)` which would be equivalent to Guava's `Iterators.indexOf`.

**Comment by lukaseder** [comment]
Excellent idea. I agree with both proposed APIs:

```java
OptionalLong indexOf(T item)
OptionalLong indexOf(Predicate<? super T> predicate)
```

The latter is also not unexpected, given the existing `Seq.findFirst(Predicate)`. I think we should prefer `OptionalLong` over the historic `-1` encoding in a primitive `long` as it fits better into the `Stream` / `Seq` API.

Would you be interested in providing a pull request for this?

**Comment by amaembo** [comment]
I have such [methods](http://amaembo.github.io/streamex/javadoc/one/util/streamex/AbstractStreamEx.html#indexOf-T-) returning `OptionalLong`. Returning -1 seems not consistent with other Stream API methods. Though probably a matter of taste.

**Comment by tlinkowski** [comment]
I am also in favor of `OptionalLong`.

OK, I'll create a pull request for this over the weekend. I propose an implementation utilizing `iterator()` and mirroring Guava's `Iterators.indexOf`.

**Comment by lukaseder** [comment]
Excellent, looking forward!

**Comment by lukaseder** [comment]
Implementation in #243
