### ISSUE TITLE
Null safe Seq constructors

### ISSUE THREAD

**Issue by pgrisafi** [jOOQ/jOOL#245]
While I'm used to always use empty collections and never use null collections, I need to maintain lots of code that does not follow such a convention. Slowly migrating to a more functional style, I found myself writing lots of `if(list != null){...}` everywhere.

So I ended up with a `Utils.safeSeq` method that returns an empty Seq if the input is null (I also used to have an `Utils.safeLoop` that returned an empty Iterable .... times are  changing)

Would it be possible to have null safe factory methods? something like

```
    static <T> Seq<T> seq(Stream<? extends T> stream, boolean emptyIfNull) {
       if(emptyIfNull && stream == null)
            return seq(Stream.empty()));

        if (stream instanceof Seq)
            return (Seq<T>) stream;

        return new SeqImpl<>(stream);
}

``` 

for every factory method? or at least for  for Seq(Iterable)? I feel kind of dirty for asking, but the code I have to work with is messy, so that's just logical.

Sorry if my English is not clear enough, and thanks for this beautiful lib!

**Comment by lukaseder** [comment]
Yeah, why not. I can see your point, and currently, the behaviour is unspecified, so we can probably change it safely.
