### ISSUE TITLE
Add static method filtered(Seq<Optional<T>>) 

### ISSUE THREAD

**Issue by tlinkowski** [jOOQ/jOOL#247]
I propose to add somewhere the following static method:

```java
static <T> Seq<T> filtered(Seq<Optional<T>> seq) {
return seq.filter(Optional::isPresent).map(Optional::get);
}
```

I currently have one so it's not of utter importance to me but I post it in case someone else finds it useful. Here's how I use it:

```java
seqOfOptionals.transform(MySeqLib::filtered)
```

instead of:

```java
seqOfOptionals.filter(Optional::isPresent).map(Optional::get)
```

Alternatively, it could be just another `Seq.seq` method. I now see there already is such a method for an array of `Optional`s so there could be another one for a `Seq` (or a `Stream`).

**Comment by lukaseder** [comment]
Hmm, JDK 9 will have [`Optional.stream()`](http://download.java.net/java/jdk9/docs/api/java/util/Optional.html#stream--), which plays very nicely with your use-case:

```java
seqOfOptionals.flatMap(Optional::stream)
```

So, I wonder if there should really be any such specific feature in jOOλ...?

**Comment by tlinkowski** [comment]
I didn't realize that. It'll be much better to have it in native Java so I close this issue.

**Comment by lukaseder** [comment]
Thanks for your feedback!
