### ISSUE TITLE
Add Seq.range(LocalDate, LocalDate) and rangeClosed(LocalDate, LocalDate)

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#248]
The default semantics of ranges between dates is to span over individual days, just like in SQL, when adding an integer interval:

```sql
DATE '2016-01-01' + 1
```

We get the next day, i.e. the interval semantics is that of `INTERVAL 1 DAY TO SECOND`

**Comment by amaembo** [comment]
See also [LocalDate.datesUntil()](http://download.java.net/java/jdk9/docs/api/java/time/LocalDate.html#datesUntil-java.time.LocalDate-) in Java 9. It was quite tricky to implement this for given Period step!

**Comment by lukaseder** [comment]
@amaembo Interesting, thanks for the feedback. I suspect that this obsoletes this issue.

Did you implement those? What were the caveats with the period step?

**Comment by amaembo** [comment]
@lukaseder yes, I implemented it. I wanted to create sized stream (in particular in Java-9 `LocalDate.now().datesUntil(blahblah).count()` is constant time), so I needed to precalculate exactly number of dates the stream should produce. This becomes tricky with periods like "1 month and 1 day" taking into account that month length is variable. Also you should carefully avoid possible overflows (e.g. `LocalDate.MIN.datesUntil(LocalDate.MAX)` has more days than `Integer.MAX_VALUE`).

**Comment by lukaseder** [comment]
Aha, yes, the constant time limitation is the issue. If the implementation is fine with linear time stream generation (which is usually the case anyway, if the stream is consumed entirely), then the periods are less of an issue.

When is the 1 month and 1 day interval of any use? In SQL, for instance, there are only two types of intervals ("periods" in JSR 310):

- `INTERVAL YEAR TO MONTH`
- `INTERVAL DAY TO SECOND`

Thus far, I have not encountered a use-case, where I would have wanted to mix the two in a single interval...

**Comment by lukaseder** [comment]
(btw: you should *definitely* start a blog. That's some extremely interesting material, here!)

**Comment by amaembo** [comment]
@lukaseder I don't think that such periods are very useful, but they are valid, thus library should support them. Even periods like "One month and minus 30 days" are valid! And they are very weird as they could have positive, zero or negative length depending on current date! Luckily I was allowed not to support them in `datesUntil`.

You mean English language blog, right? Because you should be aware that I occasionally post in Russian to Habrahabr. Ok I'll think on your suggestion (meanwhile you may learn Russian to read my posts :-))

**Comment by lukaseder** [comment]
One month and minus 30 days... What does it even mean?? :)

Yeah, I mean an English language blog. I think that would be a really great source of information for the entire Java community, plus a great way to expose yourself ([you know...](http://theoatmeal.com/comics/exposure)). I've google-translated some posts of yours in the past, but you know... :)
