### ISSUE TITLE
Add Seq.crossApply() and outerApply()

### ISSUE THREAD

**Issue by pablogrisafi1975** [jOOQ/jOOL#249]
Maybe this already exists, I can not find it.

Trying to transform my mostly business oriented code to a more functional approach, I found some pattern repeating. Lets say I have a list of headers with name and a list of details, each detail with a name and a list of subdetails, a typical nested tree. Once and again I have code like

```java
    for (Header header : headers) {
      final List<Detail> details = header.getDetails();
      if (details != null) {
        for (Detail detail : details) {
          final List<SubDetail> subDetails = detail.getSubDetails();
          if (subDetails != null) {
            for (SubDetail subDetail : subDetails) {
              System.out.println(header.getName() + " " + detail.getName() + " " + subDetail.getName());
            }
          }
        }
      }
    }
``` 
Maybe I'm not seeing something, but I can not find a way to express this in a more functional way, mostly because when using flatmat you can't access the outside loop.

I end up using tuples and manually creating methods like

```java
  public static <T1, T2, T3> Seq<Tuple3<T1, T2, T3>> unroll(List<T1> t1s, Function<T1, Collection<T2>> extractor12,
      Function<T2, Collection<T3>> extractor23) {
    List<Tuple3<T1, T2, T3>> l = new ArrayList<>();
    if (t1s != null) {
      for (T1 t1 : t1s) {
        final Collection<T2> t2s = extractor12.apply(t1);
        if (t2s != null) {
          for (T2 t2 : t2s) {
            final Collection<T3> t3s = extractor23.apply(t2);
            if (t3s != null) {
              for (T3 t3 : t3s) {
                l.add(Tuple.tuple(t1, t2, t3));
              }
            }
          }
        }
      }
    }
    return Seq.seq(l);
  }
```

and so my code becomes

```java
    final Seq<Tuple3<Header, Detail, SubDetail>> unrolled = unroll(headers, h -> h.getDetails(),
        d -> d.getSubDetails());
    unrolled.forEach(t -> System.out.println(t.v1.getName() + " " + t.v2.getName() + " " + t.v3.getName()));
```
That is way nicer and more clear, IMHO.

Still, I write this unroll methods on demand, and my naive implementation is really inefficient, I should create element as requested instead of filling an ArrayList, but that's how far I can go, my functional skills are not that good. I realize this is a weak form of for-comprehension,  but is good enough for my needs, and I think a perfect Scala-like-Java8-compatible  for-comprehension is not possible

The nicest thing about my unroll is that you can clearly separate unroll->filter->actions

```java
    final Seq<Tuple3<Header, Detail, SubDetail>> unrolled2 = unroll(headers, h -> h.getDetails(),
        d -> d.getSubDetails());
    final Seq<Tuple3<Header, Detail, SubDetail>> filtered = unrolled2
        .filter(t -> t.v3.getName().endsWith(t.v1.getName().replace("name", "")))
        .filter(t -> t.v2.getName().endsWith("2"));
    filtered.forEach(t -> System.out.println(t.v1.getName() + " " + t.v2.getName() + " " + t.v3.getName())); 
```

 Anyway: would it be possible for jool to have something like that included? I found it very useful, but maybe is the code I'm working that needs it. Or there is already something like that included, and I'm missing it?

Thanks anyway if you have read so far! And thanks for jool!

**Comment by lukaseder** [comment]
At first sight, I'm guessing you're looking for something commonly called "for comprehension", right?

**Comment by pablogrisafi1975** [comment]
It is a weaker form of for comprehension. I don't think it is possible to have real for comprehension in java without having a million of overloads for the same method, especially the guard parts signature are too complex, since you need to access the outer loop from the inner loop.

Also, I'm not so sure I want the full power, to be honest. I like jool over javaslang because it is easier to grasp and looks like "the thinks java8 missed for a little bit". javaslang is more "I want to write in Scala but my boss don't let me" 

Loop unrolling plus filtering looks just a little bit more complex that flatmap.... is basically a flatmap that gives you access to the full context. Of course, it is up to you.

Also, I was reading the Stream2 pull request, and if we have something like for n=1to16 that will work beautiful with loop unrolling, since you me work with tuples without tuples. Something like

```
unroll(headers, h -> h.getDetails(),  d -> d.getSubDetails()).forEach(h, d, sd -> System.out.println(h.getName() + " " + d.getName() + " " + s.getName()));
```
assuming  Stream3 exposes a nice foreach

**Comment by lukaseder** [comment]
Thank you very much for your additional explanations.

> javaslang is more "I want to write in Scala but my boss don't let me"

:)

I see now. So, in SQL, this would be like chaining a set of `LATERAL JOIN` (or `CROSS APPLY`) operations. I like the idea. In a first step, I don't think we should depend on the `Seq3` feature request. I'm still not 100% convinced that `Seq2`, `Seq3`, etc. is a good idea. But producing a `Seq<TupleN<...>>` sounds promising.

Perhaps, `crossApply()` would really be a good name for this. It's creating a cartesian product / cross product between the sets / streams produced when applying the various functions. What do you think?

**Comment by pablogrisafi1975** [comment]
>  I don't think we should depend on the Seq3 feature request. I'm still not 100% convinced that Seq2, Seq3, etc. is a good idea

I like the idea, but I'm not sure it is workable. I think there is going to be some unsolvable issues involving generics, covariance and contravariance and method overloading I can not identify. I wish we have Seq3, I don't want it to break Seq or Tuple3.

>Perhaps, crossApply() would really be a good name for this.

I'm not so fond in sql-inspired names. My sql skills are not so good (I don't remember ever writing or reading about `LATERAL JOIN`  or `CROSS APPLY`  operations. Is `LATERAL JOIN` the expression for `LEFT/RIGHT JOIN` ?). So it won't find a name called crossApply when looking for something that does what I need, and I'd probably feel a little scared about that name. 
Also, my use case is somewhat more limited than a cartesian product. It **is** a cartesian product, but **always** involving collections within collections. CrossApply looks more general. The signature I picture when I read crossApply is `Stream(T1, T2) crossApply (Iterable<T1> t1s, Iterable<T2> t2s)`. The signature I'm suggesting is  `Stream(T1, T2) whatever(Iterable<T1> t1s, Function<T1, Iterable<T2>> extractor12)`.

Now that I think about that, I'm sure there are some use cases for `crossApply (Iterable<T1> t1s, Iterable<T2> t2s)`. But I'm thinking in other cases right now. English is not my language, so my chances of suggesting a good name are limited... unroll? unloop?, multiFlatMap?

**Comment by lukaseder** [comment]
> I'm not so fond in sql-inspired names

Tough luck, I am :) Anyway, in the end, these are just names. No, lateral join isn't left / right join. Scared? Why? Conversely, why aren't you scared of `flatMap()`? And what would make "unroll" more obvious to find?

Truth is: FP is hard (and so is SQL), because these operations are extremely concise and meaningful, while English words are not. There's no way these things can have meaningful names. Think of the "Kleisli operator". I mean, what the hell is that?

In any case, jOOλ is opinionated and takes inspiration from SQL, which is why cross apply is a fitting name in this library (just like the window clause is, or the existing join / cross join / left right outer join are).

Note that the SQL distinction between `CROSS APPLY` and `OUTER APPLY` is just an analogy to `CROSS JOIN` and `OUTER JOIN`. I.e. it governs what happens when a `T1` value produces an empty `Collection<T2>` (cross = no result, outer = t1 stays in the result with a `NULL` value in `T2`). So, I do think we're still talking about the same thing, the signature would indeed be:

```java
Stream<Tuple2<T1, T2>> crossApply (Iterable<T1>, Function<? super T1, ? extends Iterable<T2>>)
```

**Comment by pablogrisafi1975** [comment]
> Conversely, why aren't you scared of flatMap()?

But I am!. I just think multiFlatMap is more consistent with java naming. `crossApply` would be more consistent with jOOλ, so be it. 

>  Think of the "Kleisli operator"

Why!? don't scare me!

`**Stream**<Tuple2<T1, T2>> crossApply  `  or  `  **Seq**<Tuple2<T1, T2>> crossApply ` ?

**Comment by lukaseder** [comment]
> **Stream**<Tuple2<T1, T2>> crossApply or **Seq**<Tuple2<T1, T2>> crossApply ?

`Seq` of course :)

**Comment by pablogrisafi1975** [comment]
So it was  a multiFlatMap after all
Thanks!

**Comment by lukaseder** [comment]
Almost. :) I think a method called "multiFlatMap" really just chains flatMap operations. This one here retains all the original values `T1`, `T2`, ... with the final value `TN` in a tuple.

In other words, these would be the same:

```java
multiFlatMap(seq, f1, f2, f3)
crossApply(seq, f1, f2, f3).map(Tuple4::v4)
```
