### ISSUE TITLE
Release 0.9.12 not tagged correctly, Javadoc missing on website

### ISSUE THREAD

**Issue by Xaerxess** [jOOQ/jOOL#268]
What about releasing new version of jOOL? :) 

As simple as that, I have to note that previous version (0.9.12):
- [is not tagged](https://github.com/jOOQ/jOOL/tags) 
- [does not have javadoc](http://www.jooq.org/products/jOO%CE%BB/javadoc/0.9.12/) on jooq.org.

On the other hand [it was uploaded on Maven central](https://mvnrepository.com/artifact/org.jooq/jool) and is widely used (135 usages currently). 

Can you fix 0.9.12, too?

**Comment by lukaseder** [comment]
Thanks for the pointer. Tag is now added and the Javadoc is being uploaded.

Hmm, about 0.9.13... I'd love to add some more features first, otherwise it'll be a very slim release. Do you have any ideas :)

**Comment by lukaseder** [comment]
(I'm closing this as the 0.9.12 missing tag/javadoc defect which is now fixed)

**Comment by Xaerxess** [comment]
Thanks!
