### ISSUE TITLE
Seq.grouped() returns only one group when immediately followed by a collector call

### ISSUE THREAD

**Issue by FredWanninger** [jOOQ/jOOL#271]
Hi jOOL developers,

I'm using jool 0.9.12.
I think, the abovementioned method is not working as desired, when it comes to terminal operations as toList(). In some cases, the expected group tuples are only created partly. I'm not an expert, but i think the issue has something to do with the lazyness of Seq.grouped.
Here is a minimal example with results.
```
LinkedList<Integer> inputData = new LinkedList<>();
for (int i = 0; i <= 8; i++) {
    inputData.add(i);
}

// gives (0, 012)(1, 345)(2, 678), as expected.
seq(inputData).grouped(i -> (int) (i / 3)).forEach(System.out::print);

// gives [(0, 012)] I think this is wrong.
System.out.println(seq(inputData).grouped(i -> (int) (i / 3)).toList());
```

Regards
Fred

**Comment by lukaseder** [comment]
Thanks for your report. I can reproduce this. The following test fails:

```java
    @Test
    public void testGroupedToList() {
        // [#271]
        assertEquals(
            "[(0, 012), (1, 345), (2, 67)]",
            Seq.range(0, 8)
               .grouped(i -> (int) i / 3)
               .toList());
    }
```

**Comment by lukaseder** [comment]
This will need further investigation. Unfortunately, I won't have time in the next 2-3 weeks... Of course, if you have a heads-up about the problem (I agree it has to do with laziness and the buffering of the resulting `Seq`s), I'm more than happy to review

**Comment by FredWanninger** [comment]
I might have found a solution.
In org.jooq.lambda.Seq (lines 9404ff).
According to the name, method fetchNextNewKey should be called until a new key is found. I think the boolean return values caused the opposite. Switching the values seems to fix this behavior.
```java
boolean fetchNextNewKey() {
  T next = it.next();
  K nextK = classifier.apply(next);
  Queue<T> buffer = buffers.get(nextK);
  try {
    if (buffer == null) {
      buffer = new ArrayDeque<>();
      buffers.put(nextK, buffer);
      keys.add(nextK);
      return false; // was true
    }
  }
  finally {
    buffer.offer(next);
  }
  return true; // was false
}
```

Regards
Fred

**Comment by lukaseder** [comment]
Thanks for the heads up @FredWanninger. You're right, that was probably the intention of the author. Switching the boolean return values fixes the problem for me.

Thanks again!
