### ISSUE TITLE
Add Seq.flatFold{Left,Right}

### ISSUE THREAD

**Issue by thomas001** [jOOQ/jOOL#277]
When using foldLeft, it may be useful to abort iteration, and not traverse the whole sequence. Using a Optional<T> return value might just do the trick, for example:
```java
public static <S,U> Optional<S> flatFoldLeft(Iterable<? extends U> list, 
                                             Optional<S> seed, 
                                             BiFunction<S,U,Optional<S>> func) {
    Iterator<? extends U> iterator = list.iterator();
    while(iterator.hasNext() && seed.isPresent()) {
        U nextVal = iterator.next();
        seed = func.apply(seed.get(), nextVal);
    }
    return seed;
}
```

**Comment by lukaseder** [comment]
Hmm, interesting, thanks for your suggestion. I have two questions:

- Where does the name come from? Is this a commonly used term: "flatFold"?
- What about this instead: `seq.limitUntil(something).foldLeft(seed, function)`?

**Comment by lukaseder** [comment]
I don't see much value in this additional API. I'm happy to discuss requirements / examples / use cases, but I'd like to avoid adding more features eagerly to the API.
