### ISSUE TITLE
Add branch method to the Seq interface.

### ISSUE THREAD

**Issue by GurRonen** [jOOQ/jOOL#281]
Sometimes a Seq expression may require splitting / duplicating them.

Example use cases:

* duplicating the seq to two, and unionizing them in the end. i.e sending objects to two different processors and collecting all of them to a single one.
* tagging elements in the stream by a conditional, e.g: tuples of severity to log message by count of characters
* treating the seq differently if it is of length 1, or > 1

Suggestion:

adding support for a branch method in the Seq api, which will have the following signature

```java
/** 
* implementation is quite simple, 
* duplicate().filter(conditional).map(trueMapper).concat(duplicate().filter(!conditional).map(falseMapper))
*/
Seq<A> branch(Predicate<T> conditional, Function1<T, A> trueMapper, Function1<T, A> falseMapper)

```

if i'm missing something, i'm happy to know what it is.

will add a pull request if this does not exist.

thanks!

**Comment by amaembo** [comment]
Implementation could be even simplier:

```java
map(x -> conditional.test(x) ? trueMapper.apply(x) : falseMapper.apply(x))
```

Which poses the question: is straight-forward replacement for ternary operator truly necessary?

**Comment by lukaseder** [comment]
I agree with @amaembo that the way this is currently outlined, the conditional operator seems to suffice here. But perhaps, there's a misunderstanding about what kind of use-case you intend to implement with this. Could you perhaps show some real world examples for your three bullets?

**Comment by GurRonen** [comment]
to be fair, @amaembo is right. the use cases that come up to me can be fixed with the ternary operator, it was suggested as a convenience.

another thing that comes to mind is stateful behaviour (as such will not be included in my initial issue), which would include something like: 

object T has method getNumber

```java
// current solution to this issue 
Seq<T> objSeq = Seq.of(sumT1, sumT2, sumT3, countT1, countT2);

int sum = objSeq.duplicate().filter(shouldSumPredicate::test).sum(T::getNumber);
Seq<Tuple2<Integer, T>> sumSeq = objSeq.duplicate().filter(shouldSumPredicate::test).map(o -> new Tuple2(o, sum))

int count = objSeq.duplicate().count();
Seq<Tuple2<Integer, T>> countSeq = objSeq.filter(normalsPredicate::test).map(o -> new Tuple2(o, count))

Seq<Tuple2<Integer, T> resultSeq = sumSeq.concat(countSeq)
```

this example i'm seems pretty useless. but i hope the concept comes through.

the use case is when requiring a stateful pass on the seq, based on a conditional it is problematic to apply with seq (not that it is possible with Streams)


I'm not sure for a clean solution for this. any ideas?

**Comment by GurRonen** [comment]
Just saw the window function in the Seq interface, closing.
