### ISSUE TITLE
Move Async to org.jooq.lambda package

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#287]
@billoneil I've noticed only now that you've created a new subpackage `concurrent`. I wonder if we'll need that. I somewhat regret the existing packages. Would you agree to moving this to `org.jooq.lambda`?

----

API was not published yet prior to 0.9.13, so this isn't a breaking change.

**Comment by billoneil** [comment]
Sure whatever package you prefer.

**Comment by billoneil** [comment]
Should all the classes move?
