### ISSUE TITLE
Throwing Excptions via Optionals?

### ISSUE THREAD

**Issue by Spike2050** [jOOQ/jOOL#295]
Hi lukaseder

I have a question about the sneakythrow function. You throw any Throwable with these methods

```java
static void sneakyThrow(Throwable throwable) {
    SeqUtils.<RuntimeException>sneakyThrow0(throwable);
}

@SuppressWarnings("unchecked")
static <E extends Throwable> void sneakyThrow0(Throwable throwable) throws E {
    throw (E) throwable;
}
```
I don't understand how you can do that, how can you cast any Exception to a RuntimeException, without the compiler complaining?

You could use this to throw Exceptions inside a sequence lambda if you add a function to Seq.java like this:
```java
default <X extends Throwable> Seq<T> onOptionalThrow(Function<? super T, Optional<? extends X>> function) {
    return peek(e -> {
        Optional<? extends X> opt = function.apply(e);
        if (opt.isPresent()) {
            sneakyThrow(opt.get());
        }
    });
}
```
You could use this function to do stuff like this:
```java
Seq.of(1, 2, 3).onOptionalThrow(t -> {
     if (t > 3) {
        return Optional.of(new Exception());
    }
    return Optional.empty();
}).toList();
```
I wrote a test and it seems to work, but I can't confidently say why. Why is this a bad idea or what have i forgotten.

**Comment by lukaseder** [comment]
Yeah, that's magic, isn't it? The `RuntimeException` generic type binding does not result in a type cast, so there's no class cast exception. However, it does trick the compiler into believing that the exception being thrown is unchecked.

Hope this helps

**Comment by Spike2050** [comment]
Well wait :-)

Are you interested to add this function into the library:
```java
default <X extends Throwable> Seq<T> onOptionalThrow(Function<? super T, Optional<? extends X>> function) {
    return peek(e -> {
        Optional<? extends X> opt = function.apply(e);
        if (opt.isPresent()) {
            sneakyThrow(opt.get());
        }
    });
}
```
You could throw exceptions without converting them to RunitmeException inside a long Sequence chain and without a surrounding try-catch-block.

**Comment by lukaseder** [comment]
Aha, I see. Sorry, I misunderstood - thought you were just showing an example. I currently don't see this functionality as interesting enough to add to the `Seq` API.  Your suggested example:

```java
Seq.of(1, 2, 3).onOptionalThrow(t -> {
     if (t > 3) {
        return Optional.of(new Exception());
    }
    return Optional.empty();
}).toList();
```

Can be easily replaced by this:

```java
Seq.of(1, 2, 3).peek(t ->{
    if (t > 3)
        sneakyThrow(new Exception());
}).toList();
```

I mean, why do you want to hide this `sneakyThrow()` API? Because of the word "sneaky"?

**Comment by Spike2050** [comment]
Yes you could do it that way, but then why do you give the option of Unchecked.consumer, when you could just sneakyThrow?

**Comment by Spike2050** [comment]
But you are right, if you see it from that perspective my function is unnecessary.

**Comment by lukaseder** [comment]
`Unchecked.consumer` wraps a functional interface in a slightly different behaving functional interface, which works wherever a consumer is required.

`sneakyThrow` throws an exception immediately. I think the two concepts are rather orthogonal, don't you think? But indeed, explicit `sneakyThrow` could be omitted with this pattern:

```java
Seq.of(1, 2, 3).peek(Unchecked.consumer(t -> {
    if (t > 3)
        throw new Exception();
})).toList();
```

**Comment by Spike2050** [comment]
Yes, the thing is, if I package a checked Exception in an unchecked Exception I have to "unpack" it outside the stream with a throw/catch block to throw it correctly, if the surrounding function needs to throw this exception. I had this use case several times.
If you can ommit that with sneakyThrow, good. You should promote this in your readme, I only found out about it by looking into the code.

**Comment by lukaseder** [comment]
You're right, thanks for the suggestion. Added a section right now:
https://github.com/jOOQ/jOOL/commit/74c4bc99d59afd5a82bdfe309b23e825f4bb0e5d#diff-04c6e90faac2675aa89e2176d2eec7d8
