### ISSUE TITLE
Add static Seq.iterateWhilePresent/iterateUntilAbsent

### ISSUE THREAD

**Issue by tlinkowski** [jOOQ/jOOL#303]
Method `static Seq<T> iterateWhilePresent(T seed, Function<? super T, Optional<? extends T>> generator)` would iterate until the generator returns an empty `Optional`.

Example, non-optimal implementation (with nullable `seed`) would be:
```java
UnaryOperator<Optional<? extends T>> f = optional -> optional.flatMap(generator::apply);
return Seq.iterate(Optional.ofNullable(seed), f).limitWhile(Optional::isPresent).map(Optional::get);
````

Rationale: if we have a tree-like structure where each node stores a nullable reference to its parent (null if no parent), the "ancestry line" of the tree can easily be found using `Seq.iterateWhilePresent(treeNode, TreeNode::findParent)` where `TreeNode.findParent()` returns `Optional<TreeNode>`.

PS. It would be equivalent to https://github.com/poetix/protonpack#unfold

**Comment by lukaseder** [comment]
That's interesting. Do note there will be a similar method in Java 9's `Stream`
http://download.java.net/java/jdk9/docs/api/java/util/stream/Stream.html#iterate-T-java.util.function.Predicate-java.util.function.UnaryOperator-

I guess from an implementation perspective, we could definitely take inspiration from there. If I remember correctly, @amaembo implemented that, or at least tuned it quite nicely.

I somehow prefer the boolean type as an indicator of stream termination, as that goes well with the existing `limitWhile()` and similar methods...

What do you think?

**Comment by tlinkowski** [comment]
Oh, I didn't realize Java 9 will have that - thanks for pointing that out to me! As to what I think, I think this Java 9's API is actually worse :) I mean, it's like `Iterator` where you have separate logic for `hasNext` and `next` when quite often they correspond to the same (possibly expensive) operation. Even in `Spliterator` they gave it up for a single method (`tryAdvance`). And in Guava, they have `AbtractIterator` that also has only one method (`computeNext`).

Note that if you wanted to apply this Java 9's API to the `TreeNode` example I mentioned earilier (with its `findParent()` returning `Optional`), it would be quite cumbersome (`Stream.iterate(Optional.of(treeNode), Optional::isPresent, optional -> optional.get().findParent()).map(Optional::get)`).

I'm not sure if it's good practice but right now I use `Optional` as return type almost everywhere where I previously used `@Nullable`, and that's why I much prefer this `Optional`-based API.

**Comment by tlinkowski** [comment]
I gave it a second thought, and I came to think the Java 9's API is actually quite OK because you can just write:
```java
return Stream.iterate(treeNode, Objects::nonNull, treeNode -> treeNode.findParent().orElse(null));
```

Of course, I still prefer the `Optional`-based version in this particular case, but I think having both of them would be the best solution.

**Comment by lukaseder** [comment]
I had the same concerns about the `Predicate` based version. While in many cases, it might be possible to find a solution where the `Predicate` is trivial, there might some link between the predicate calculation and the next value calculation...

Well, I guess we'll get the `Predicate` version "for free" as soon as JDK 9 is out. I'm OK with your suggestion and the names. Would you be interested in providing a PR?

**Comment by tlinkowski** [comment]
Sure. I'll implement it using `Seq.limitWhile`, and when jOOλ switches to Java 9, the new `Stream.iterate` can be utilized instead.
