### ISSUE TITLE
Seq.limitUntil sometimes fetches too many elements from source

### ISSUE THREAD

**Issue by tlinkowski** [jOOQ/jOOL#309]
When calling `Seq.of(1, 2, 3, 4, 5).limitUntil(i -> i > 1).iterator()`, and then calling `Iterator.next()` until `!Iterator.hasNext()`, two elements are fetched from the source `Seq` (`1` that fails the `Predicate`, and `2` that satisfies the `Predicate`), which is correct behavior.

However, when calling `Iterator.hasNext()` one more time (which is redundant but valid), one more element (`3`) is fetched from the source `Seq`, which is incorrect behavior.

This behavior breaks some code, e.g. the following:
```java
interface Node {
  @Nullable Node parent();
}

static Seq<Node> ancestorSeq(Node node) {
  return Seq.iterate(node, Node::parent).limitUntil(Objects::isNull);
}
```

PS. All the other methods (`limitUntilClosed`, `skipUntil`, `skipUntilClosed`) work correctly.

**Comment by tlinkowski** [comment]
Oh, I found out where this defect comes from: in `Seq.limitUntil` the condition `!test[0]` must be tested before (and not after) calling `delegate.tryAdvance`:
```java
!test[0] && delegate.tryAdvance(t -> {
    if (!(test[0] = predicate.test(t)))
        action.accept(t);
})
```

**Comment by lukaseder** [comment]
Thank you very much for your analysis. I can confirm that your suggested solution works. Interestingly, `limitUntilClosed` does it correctly with the proper order of booleans in the expression...
