### ISSUE TITLE
limitWhile (and other limit* methods) problem

### ISSUE THREAD

**Issue by cigaly** [jOOQ/jOOL#318]
This test will generate ArrayIndexOftOfBoundsException:

    @Test
    public void limitWhite() {
        Integer array[] = { 1, 2, -1 };
        UnaryOperator<Integer> iterate = x -> array[x];
        Predicate<Integer> filter = x -> x >= 0;
        
        Seq<Integer> seq1 = Seq.iterate(0, iterate);
        Seq<Integer> seq2 = seq1.limitWhile(filter);
        // After limitWhile seq2 should be { 0, 1, 2 }
        Seq<Integer> seq3 = seq2.map(x -> x + 1);
        // After map seq3 should be { 1, 2, 3 }
        int seq4 = seq3.foldLeft(1, (x, y) -> x * y);
        // Rezult should be 6
        Assert.assertEquals(6, seq4);
    }

After filter predicate.test(-1) returns false, iterate.apply(-1) should newer be called.

Here is equivalent code in scala that is working as expected:

```scala
val array = Array(1, 2, -1)
def str(x: Int): Stream[Int] = x #:: str(array(x))
val seq1 = str(0)
val seq2 = seq1.takeWhile(x => x >= 0)
val seq3 = seq2.map(x => x + 1)
val seq4 = seq3.foldLeft(1)((x, y) => x * y)
```

**Comment by lukaseder** [comment]
Thank you very much for reporting. Will look into this immediately.

**Comment by lukaseder** [comment]
It might well be that jOOλ could optimise the lazy evaluation of the `Seq.iterate()` calls (currently passing this through to `Stream`) to avoid the application of the call `array[-1]`, but in any case, defensive programming would probably suggest this implementation, instead:

```java
UnaryOperator<Integer> iterate = x -> x >= 0 ? array[x] : x;
```

**Comment by cigaly** [comment]
You are right, it could be coded that way, still, I would not call that a feature.

**Comment by lukaseder** [comment]
> still, I would not call that a feature.

Well, I didn't, did I? :)

![image](https://user-images.githubusercontent.com/734593/27742841-6c1e7018-5dba-11e7-9f1d-9e12df65c8cf.png)

**Comment by cigaly** [comment]
No, that's true :-)

**Comment by tlinkowski** [comment]
This issue is a duplicate of #309 :) Fortunately, it's trivial to fix - see https://github.com/jOOQ/jOOL/issues/309#issuecomment-298250192.

**Comment by cigaly** [comment]
That's correct. With your proposed change thsi is working properly.
