### ISSUE TITLE
Type inference regressions when compiling with JDK 9

### ISSUE THREAD

**Issue by fupfin** [jOOQ/jOOL#323]
### Expected behavior and actual behavior:
Even pom.xml's compiler plugin is configured using java 1.8 spec, I can not compile jOOL with JDK 9. In JDK 8, I can compile jOOL with no error.

[out.txt](https://github.com/jOOQ/jOOL/files/1385241/out.txt)

### Steps to reproduce the problem:
1. Clone jOOL from github project
2. cd jOOL
3. mvn compile

### Versions:

- jOOλ: master/HEAD
- Java: java build 9+181

**Comment by lukaseder** [comment]
Thanks for your report. Indeed, I can reproduce this issue. Probably a bug in the JDK compiler, but maybe we can work around it for the time being.

**Comment by fupfin** [comment]
Thank you. I can compile jOOL without any errors, now.
