### ISSUE TITLE
Add sources.jar to the latest (0.9.13) Maven release

### ISSUE THREAD

**Issue by tlinkowski** [jOOQ/jOOL#332]
I started using jOOL 0.9.13 but there is no `sources.jar` file in Maven Central Repo so when I want to inspect any jOOL class/method I see decompiled bytecode instead, which is annoying.

Please, add `sources.jar` to the release, if possible.

http://search.maven.org/#search%7Cga%7C1%7Cjool

### Versions:

- jOOλ: jool:0.9.13, jool-java-8:0.9.13

**Comment by lukaseder** [comment]
Thanks for pointing this out. Indeed - weird there was no error from Sonatype. I'll look into this soon

**Comment by lukaseder** [comment]
Yeah, easy. The `maven-source-plugin` was accidentally removed when implementing #327.

Re-added the plugin: https://github.com/jOOQ/jOOL/commit/f24fbfc1339fbbf819cf088364733ce8e4754fae. Let's see if Maven Central allows for re-deploying only the sources.jar file, otherwise we'll need a 0.9.14 release...

**Comment by lukaseder** [comment]
Seems to have worked on the Sonatype console. Let's wait and see if the publication shows up correctly...

**Comment by ansell** [comment]
The timestamps are a little strange, as if the ``sources.jar`` was previously deployed correctly, but the files are there:

https://repo.maven.apache.org/maven2/org/jooq/jool/0.9.13/

Search.maven.org is still showing the ``source.jar`` file as not being there in its interface, but it can be accessed using:

https://search.maven.org/remotecontent?filepath=org/jooq/jool/0.9.13/jool-0.9.13-sources.jar

**Comment by lukaseder** [comment]
Thanks for the feedback, @ansell. Indeed, the timestamps are interesting, also interesting that not all files have been produced, e.g. the `asc.md5` and `asc.sha1` hashes are missing. Perhaps that's the reason why the search doesn't display it.

Downloading the sources using Eclipse seems to work, however, so I'll close this issue for now - I can live with this flaw.

I hope to be able to finally allocate some time to review @tlinkowski's many PR's from last year (really sorry for the delay!), so a version 0.9.14 might be published within some months.
