### ISSUE TITLE
Compile error using Jool with Eclipse and Java11

### ISSUE THREAD

**Issue by cvgaviao** [jOOQ/jOOL#343]
### Expected behavior and actual behavior:
I'm getting a "CheckedFunction cannot be resolved to a type" compile error. The same is happening to all others Jool classes.

I'm expecting to get any error message.

### Steps to reproduce the problem:
I added the recommended maven dependency:

```
<dependency>
  <groupId>org.jooq</groupId>
  <artifactId>jool</artifactId>
  <version>0.9.13</version>
</dependency>
```

One thing to note is that my project is set to be targeted to java11:

```        
       <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
          <configuration>
            <source>11</source>
            <target>11</target>
            <release>11</release>
          </configuration>
        </plugin>
```

### Versions:

- jOOλ: 0.9.13
- Java: java version "11.0.1" 2018-10-16 LTS
- Eclipse: Version: 2018-12 (4.10.0) Build id: 20181214-0600

**Comment by cvgaviao** [comment]
I found a workaround inside Eclipse. 
I needed to open the project properties and change the "Compiler compliance level" to java8

**Comment by lukaseder** [comment]
Thanks for your message. Indeed, this definitely looks like an Eclipse problem more than a jOOλ problem. Glad you could find a solution.

**Comment by cvgaviao** [comment]
Well, besides I have found a workaround, that is temporary and turns to issue the error again after I use the m2e update project command.
But what is annoying me is that this error starts to happen only I've introduced jool to my stack this week. any other lib is issuing this error...

**Comment by cvgaviao** [comment]
I have opened an issue in Eclipse JDT Bugzilla: https://www.eclipse.org/forums/index.php/m/1800445/

**Comment by cvgaviao** [comment]
@lukaseder, the issue described here is not occurring with version 0.9.14.

**Comment by lukaseder** [comment]
I've given up on using Eclipse with modular things like jOOλ. If you want to use the Java-8 compatible jOOλ, you can use the `jool-java-8` artifact.
