### ISSUE TITLE
Reject method to Seq stream

### ISSUE THREAD

**Issue by strogiyotec** [jOOQ/jOOL#346]
It would be good if JOOL will have an analog of Ruby's reject method which is opposite to filter method (remove element if matched)

**Comment by lukaseder** [comment]
You can simply write `Seq.filter(Predicate.not(mypredicate))`.

**Comment by strogiyotec** [comment]
In my opinion
```
Seq.of(1,2,3,4,5).reject(p->p>2)
```
is more clear . What do you think ?

**Comment by lukaseder** [comment]
What's unclear about this?

```java
Seq.of(1,2,3,4,5).filter(p->p<=2)
```
