### ISSUE TITLE
JOOL miss CheckedToBooleanFunction

### ISSUE THREAD

**Issue by strogiyotec** [jOOQ/jOOL#347]
JOOL has a lot of interfaces which convert generic type T to primitive type like
```
CheckedToDoubleFunction
CheckedToIntFunction
```
it would be nice to have
```
CheckedToBooleanFunction
``` 
that accepts generic type and return boolean

**Comment by lukaseder** [comment]
You're looking for [`CheckedPredicate`](https://www.jooq.org/products/jOO%CE%BB/javadoc/0.9.14/org/jooq/lambda/fi/util/function/CheckedPredicate.html). The name is derived from the JDK's functional interface types.
