### ISSUE TITLE
jool-java-8 has major version 53 (JDK9)

### ISSUE THREAD

**Issue by vbaidak** [jOOQ/jOOL#349]
### Expected behavior and actual behavior:
Expected: major version is **52**
Actual: major version is **53**

### Steps to reproduce the problem:
run the code in JRE 8

### Versions:

- jOOλ: org.jooq:jool-java-8:0.9.13+
- Java: Oracle JDK 8

### Stacktrace
```
Failed to define class org.jooq.lambda.fi.util.function.CheckedFunction in Module "deployment.identity.war" from Service Module Loader: java.lang.UnsupportedClassVersionError: Failed to link org/jooq/lambda/fi/util/function/CheckedFunction (Module "deployment.identity.war" from Service Module Loader): org/jooq/lambda/fi/util/function/CheckedFunction has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

**Comment by lukaseder** [comment]
I'm assuming this resolved itself? I cannot confirm that `jool-java-8` has the wrong version number.

**Comment by vbaidak** [comment]
Yes, @lukaseder . I had both jool dependencies in classpath, so it was my mistake. Sorry for taking your time

**Comment by sdykae** [comment]
When
` major version 53 is newer than 52, the highest major version supported by this compiler.`
use 
```
implementation("org.jooq:jool-java-8:0.9.14")

```
instead 
```
implementation("org.jooq:jool:0.9.14")
```
