### ISSUE TITLE
Add support for unbounded ranges

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#350]
The `org.jooq.lambda.tuple.Range` type currently supports only bounded ranges. It would be nice to support also unbounded ranges, where `null` corresponds to "infinity".

For example:

```java
// From 1 to infinity
new Range(1, null);

// From -infinity to 1
new Range(null, 1);
```

**Comment by tlinkowski** [comment]
Just for reference (in case you wanted to further improve your ranges), [Guava](https://github.com/google/guava/wiki/RangesExplained) has quite advanced range support (including e.g. open/closed bounds).

**Comment by Artus2b** [comment]
@tlinkowski Indeed I found the Guava and Apache Common Ranges implementations, while I was writing the algorithm of `overlaps(Range a, Range b)` that was a bit cumbersome.
Are you saying those libs nullify the usefulness of the issue? Or that we should use Guava's implementation in the proposed fix?

**Comment by tlinkowski** [comment]
> Are you saying those libs nullify the usefulness of the issue? Or that we should use Guava's implementation in the proposed fix?

@Artus2b I don't know which is best here. In your PR, you mentioned how it works in PostgreSQL, so aligning to its Range Types (independently of other libs) in certainly one option.

To sum up, I'm just saying it's good to be *aware* of other solutions (thx for mentioning Apache Commons - forgot about that) so that an informed decision can be made.

**Comment by lukaseder** [comment]
> Are you saying those libs nullify the usefulness of the issue?

Everything jOOλ does is available in one way or another through a different means. After all, we're all working with turing complete languages, so everything is possible, including NIH, home grown solutions to every single problem :)

Given that we already have a `Range` type, it's definitely worth exploring what else it can offer, and I do like this idea, regardless of what Guava does.

**Comment by lukaseder** [comment]
I think that all changes from your PR are now addressed:

- Documentation of inclusivity of current range implementation
- (Partially) Unbounded ranges
- `Range.contains()`

Thanks again for your suggestion and PR.
