### ISSUE TITLE
Let Function interfaces implement Serializable

### ISSUE THREAD

**Issue by vusalalishov** [jOOQ/jOOL#356]
### Expected behavior and actual behavior:
I use `Function` interfaces in Apache Wicket application and it would be great if they would be Serializable.

### Steps to reproduce the problem:
Try to use one of `Function` interfaces with Apache Wicket.

### Versions:
- jOOλ: all versions
- Java: 8+

Is it possible to add `Serializable` to `Function` interfaces?

**Comment by lukaseder** [comment]
Thanks for your suggestion. I would really rather not make anything serializable in jOOλ as we'd have to support serializability, which is such a pain for so little gain... See e.g. http://cr.openjdk.java.net/~briangoetz/amber/serialization.html

The JDK functional interfaces are also not serializable, for the record, so chances are you wouldn't actually gain much.
