### ISSUE TITLE
Treat null as empty array in Seq.of(T[])

### ISSUE THREAD

**Issue by pgrisafi** [jOOQ/jOOL#358]
Not an issue but an enhancement.

Some time ago I asked for a [null-safe Seq constructor for lists](https://github.com/jOOQ/jOOL/issues/245), because I work with lots of legacy code and I found myself writing lots of
  
    list == null ? Seq.empty() : Seq.seq(list)

and you were kind enough to implement it

Now I'm back asking for the same thing for arrays, since I'm still handling lots of legacy code and I found myself writing lots of

    array == null ? Seq.empty() : Seq.of(array)

Would that be possible?

### Expected behavior and actual behavior:

Expected:

    Assertions.assertEquals(0, Seq.of((Object[])null).count());

Actual:
 
    throws a java.lang.NullPointerException

P.S.: and what about an overload for `Seq.seq(Object[] array)` to make the library more consistent? I'm not so sure if this is possible since there is already a 

     Optional<? extends T>... optionals)

### Versions:

- jOOλ: all of them
- Java: all of them

Again, sorry if my English is not clear enough, and thanks for this beautiful lib!

**Comment by lukaseder** [comment]
Thank you very much for your suggestion. I agree it would be consistent for `Seq.of(T[])` to accept `null` arrays just like empty arrays.

We actually already have `seq(T[], int, int)`. I'm not sure why there's no `seq(T[])` overload, so I agree with both of your suggestions.
