### ISSUE TITLE
Add Agg.stddev() and variance() and similar aggregate functions

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#360]
It would be useful to be able to calculate some statistics functions like `stddev`, `variance` and other things, including linear regression functions.

**Comment by Lu-Jichen** [comment]
I would like to work on this issue. I think to make the function more clear and easy to use, a mapping function which can map the object to a double value is needed. The return value should also be a double value, which is the standard deviation or the variance.

**Comment by lukaseder** [comment]
Integrated with some minor improvements. Thanks again for your efforts!
