### ISSUE TITLE
Wrong result for Agg.regrR2Double()

### ISSUE THREAD

**Issue by magicprinc** [jOOQ/jOOL#397]
This is not something I have made.
I checked out last sources from jOOQ/jOOL repo and ran maven:
The test has failed.

```
[ERROR] Failures:
[ERROR]   CollectorTests.testRegrR2:1472 expected:<Optional[1.0]> but was:<Optional.empty>`

[ERROR] Tests run: 52, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.114 s <<< FAILURE! - in org.jooq.lambda.CollectorTests
[ERROR] org.jooq.lambda.CollectorTests.testRegrR2  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: expected:<Optional[1.0]> but was:<Optional.empty>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.jooq.jool/org.jooq.lambda.CollectorTests.testRegrR2(CollectorTests.java:1472)
```

I don't use it, so I don't dare to touch it.

**Comment by lukaseder** [comment]
Thanks, can confirm. Will look into this soon

**Comment by lukaseder** [comment]
The test is correct. The expected result is `1.0`:

```sql
select regr_r2(x, y)
from (values (1, 1), (1, 2)) t (x, y)
```

Produces:

```
|regr_r2|
|-------|
|1      |
```

**Comment by lukaseder** [comment]
https://github.com/jOOQ/jOOQ/issues/11547 defines `REGR_R2` as:

```sql
REGR_R2(x, y) = CASE 
  WHEN VAR_POP(NVL2(x, y, NULL)) = 0 THEN NULL 
  WHEN VAR_POP(NVL2(y, x, NULL)) = 0 THEN 1 
  ELSE CORR(x, y)^2 
END
```

**Comment by lukaseder** [comment]
The formula is implemented correctly, but the internal `mapAll(Tuple3<Optional<T1>, Optional<T2>, Optional<T3>>)` isn't. It's requires all optionals to be non-empty in order to map anything, when in fact this isn't what the `CASE` expression suggests.

**Comment by lukaseder** [comment]
Well, `mapAll()` is implemented correctly, but using it is wrong.

**Comment by lukaseder** [comment]
The reason why this hasn't been detected in our CI is because we recently migrated CI and jOOλ wasn't part of the new installation...
