### ISSUE TITLE
Avoid ClassCastException in TupleN.compareTo()

### ISSUE THREAD

**Issue by lukaseder** [jOOQ/jOOL#51]
Right now, it is simply assumed that all tuple attributes are also `Comparable` when calling `TupleN.compareTo()`. It would be better to either:
- Fail with a more explicit runtime exception
- Silently ignore those types (that might conflict with the `SortedSet` contract recommendations)

**Comment by jmiettinen** [comment]
Is having a separate Tuple class (probably a sub-class) that's actually `Comparable` out of the question?
That would make it explicit and type-checkable when you have `Tuple` and when you have `OrderedTuple`.

It does have compatibility concerns and makes interfaces that want to be co/contra-variant more cumbersome.

**Comment by lukaseder** [comment]
@jmiettinen I had thought about that at some point. The problem is, we'll need to duplicate each of the `Tuple[N]` classes to be also represented as `ComparableTuple[N]`. And then, perhaps, we'll want to do the same for `Serializable`, and for...

Ultimately, I think that the `Comparable` semantics in Java is just a bit of a historic mess. It is not always possible to be type safe with `Comparable`. E.g. in SQL, tuples are always comparable (`ORDER BY`) but they may still contain `BINARY` types, which cannot be ordered. Sometimes, a runtime exception is the best (most pragmatic) solution to a problem.

This issue only criticises the use of `ClassCastException`, which is not very clear.

**Comment by jmiettinen** [comment]
Yes, trying to support combinations of N different interfaces is a hassle, to say the least. And I've perhaps hijacked a wrong issue here.

I don't, however, understand the point about `Comparable` and SQL binary types. I've thought that `Comparable` has quite clearly defined semantics as long as we ignore the sub-typing problems there can be, similar to `equals`. That doesn't seem relevant here as there should not be subclasses of Tuples?

**Comment by lukaseder** [comment]
> I don't, however, understand the point about Comparable and SQL binary types

Imagine a `Tuple3<String, Integer, byte[]>`. While the `Tuple3` in general is always comparable, it is no longer so as soon as it contains (for example) binary types.

**Comment by lukaseder** [comment]
According to the `Comparable.compareTo()` Javadoc, a `ClassCastException` is precisely what should be thrown, so the current behaviour is fine.
