### ISSUE TITLE
How do you compile jOOL from sources (with tests)?

### ISSUE THREAD

**Issue by cdshines** [jOOQ/jOOL#86]
I checked out the source code from git (master branch), `mvn compile` works fine, while `mvn test` does not, it fails with the following exceptions:

	[ERROR] /home/jOOL/src/test/java/org/jooq/lambda/TupleTest.java:[144,72] error: incompatible types: cannot infer type-variable(s) U2
	[ERROR] 
		U2 extends Object declared in method <U2>map2(Function1<? super T2,? extends U2>)
		T2 extends Object declared in class Tuple4
		T1 extends Object declared in class Tuple4
		T3 extends Object declared in class Tuple4
		T4 extends Object declared in class Tuple4
		
and a lot of:

	[ERROR] class SeqTest
    [ERROR] /home/IdeaProjects/jOOL/src/test/java/org/jooq/lambda/SeqTest.java:[126,11] error: cannot find symbol
    [ERROR] class SeqTest
    [ERROR] /home/IdeaProjects/jOOL/src/test/java/org/jooq/lambda/SeqTest.java:[127,11] error: cannot find symbol
    [ERROR] class SeqTest
    [ERROR] /home/IdeaProjects/jOOL/src/test/java/org/jooq/lambda/SeqTest.java:[122,64] error: cannot find symbol
    [ERROR] class SeqTest
    [ERROR] /home/IdeaProjects/jOOL/src/test/java/org/jooq/lambda/SeqTest.java:[144,11] error: cannot find symbol
    [ERROR] class SeqTest
    [ERROR] /home/IdeaProjects/jOOL/src/test/java/org/jooq/lambda/SeqTest.java:[145,11] error: cannot find symbol
    [ERROR] class SeqTest
    [ERROR] /home/IdeaProjects/jOOL/src/test/java/org/jooq/lambda/SeqTest.java:[146,11] error: cannot find symbol
    [ERROR] class SeqTest
    [ERROR] /home/IdeaProjects/jOOL/src/test/java/org/jooq/lambda/SeqTest.java:[147,11] error: cannot find symbol
    [ERROR] class SeqTest
    [ERROR] /home/IdeaProjects/jOOL/src/test/java/org/jooq/lambda/SeqTest.java:[148,11] error: cannot find symbol
    [ERROR] class SeqTest
	

I've written a couple of lines which I would like to propose in the pull request, but I can't run tests for them, so I'm stuck here. What should I do to launch jOOL tests?

More info:

	~|⇒ java -version
    java version "1.8.0_31"
    Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
    ~|⇒ mvn -version
    Apache Maven 3.0.5
    Maven home: /usr/share/maven
    Java version: 1.8.0_31, vendor: Oracle Corporation
    Java home: /usr/lib/jvm/java-8-oracle/jre
    Default locale: en_US, platform encoding: UTF-8
    OS name: "linux", version: "3.13.0-45-generic", arch: "amd64", family: "unix"
    ~|⇒ javac -version
    javac 1.8.0_31

**Comment by lukaseder** [comment]
It works for me, but beware that there had been tons of bug fixes in recent versions of all compilers (Java, Eclipse, etc.). Please upgrade to the latest Java version:

```
C:\Users\Lukas\workspace\jOOL>java -version
java version "1.8.0_40-ea"
Java(TM) SE Runtime Environment (build 1.8.0_40-ea-b23)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

Looking forward to your pull request...
