### ISSUE TITLE
Question: Singleton Seq of Array

### ISSUE THREAD

**Issue by danieldietrich** [jOOQ/jOOL#89]
Hi Lukas,

I'm not convinced about the `java.util.stream.Stream.of()` API. There are

* `Stream.of(T t)` respectively `Seq.of(T t)`
* `Stream.of(T... values)` respectively `Seq.of(T... values)`

which does not allow us to create a Stream/Seq of an Array, i.e.

* `Seq.of(new String[] { "hello" })` is a `Seq<String>` instead of a `Seq<String[]>`

Workaround:

* `Seq.of(new String[][]{{ "" }})`, which is ugly

Just want to hear your opinion about the practical value of having a special API for a singleton Array Seq.

And also: What is the use case for a `Stream.of(T t)`. If there would be only a `Stream.of(T... values)` we could also call `Stream.of(t)`!? Looking at the implementation of java.util.stream.Stream.of(T t) I see a difference, but from the API perspective I don't see the point.

\- Daniel

**Comment by lukaseder** [comment]
> Just want to hear your opinion about the practical value of having a special API for a singleton Array Seq.

It's simple. The use-case of `Seq.of(1, 2, 3, 4, 5)` is just more useful and common than the use-case of `Seq.of(new String[][] {{ "" }})`. So, this API is a compromise worth making, although I see your point. Another workaround:

```java
Seq.of((Object) new String[] { "" });
```

> Looking at the implementation of java.util.stream.Stream.of(T t) I see a difference, but from the API perspective I don't see the point.

Less pressure on the GC due to unneeded array references? `EnumSet.of(...)` took this even further

**Comment by danieldietrich** [comment]
Thanks, I thought I've overseen s.th.

I like varargs, too. A little bit nasty is the need for `@Safeargs` and `@SuppressWarnings("unchecked")` in general (for API designers).

An alternative for creating a singleton would be another method name, like `Seq.singleton(String[] { "" })`. However, `Seq` reflects the java `Stream` API and I think here is nothing to do.

My question is clarified, the issue can be closed :-)

Thanks again!
\- Daniel

**Comment by lukaseder** [comment]
> A little bit nasty is the need for `@SafeVarargs`

You're telling me? I'm maintaining a huge Java-6 compatible API (jOOQ). I could kick someone for not having introduced `@SafeVarargs` any earlier :-) (and in a better way)

> An alternative for creating a singleton would be another method name, like `Seq.singleton`

Yes, that would match the existing `java.util.Collections.singleton()`.

> However, Seq reflects the java Stream API and I think here is nothing to do.

Yes. Good enough for "us". You can do better, in Javaslang :-)

**Comment by danieldietrich** [comment]
That's fair enough :-)

**Comment by lukaseder** [comment]
I've just thought of another reason why you should overload `method(T)` and `method(T...)`:
http://blog.jooq.org/2014/09/19/learn-how-nashorn-prevents-effective-api-evolution-on-a-new-level/

**Comment by danieldietrich** [comment]
Thank you for sharing! That was insightful, there is so much to learn!

Also interesting how deep and thoughtful are little things which seem to be trivial at first sight.

**Comment by jbgi** [comment]
I think the proper work around is
`` Stream.<String[]> of(new String[] { "hello" }); ``

**Comment by lukaseder** [comment]
@jbgi: Yes, you're right

**Comment by danieldietrich** [comment]
@jbgi it is 6 chars longer than `Stream.of(new String[][]{{"hello"}});` but way less ugly :-)

**Comment by danieldietrich** [comment]
Just for the sake of completeness:

> And also: What is the use case for a Stream.of(T t). If there would be only a Stream.of(T... values) we could also call Stream.of(t)!? Looking at the implementation of java.util.stream.Stream.of(T t) I see a difference, but from the API perspective I don't see the point.

It's the `null` - `Stream.of(T... values)` throws when called with null arg.

**Comment by lukaseder** [comment]
> It's the null - Stream.of(T... values) throws when called with null arg.

Interesting point, I haven't thought of this... This is probably relevant only when passing a `null` literal such as `of(null)`, though, which should intuitively correspond to `of((Object) null)`, but of course doesn't, really meaning `of((Object[]) null)`
