### ISSUE TITLE
Add Seq.isEmpty/nonEmpty()

### ISSUE THREAD

**Issue by stephenh** [jOOQ/jOOL#94]
Just a short cut for .count() == 0 or .count() > 0, which the Scala collections have.

(Not sure if you explicitly left them out, nor necessarily asserting "just because Scala has it, jOOL should too".)

(Also, sorry, should be submitting pull requests, but I was having some problems with Eclipse and so am taking the lazy approach for now.)

**Comment by lukaseder** [comment]
That makes sense

> (Not sure if you explicitly left them out, nor necessarily asserting "just because Scala has it, jOOL should too".)

We've been adding methods on demand or when we needed them ourselves

**Comment by lukaseder** [comment]
However, I don't agree on the shortcut for `count()`. `count()` can be an awfully heavy operation when we just want to check the sequence for the presence of "any" element. We should use `findAny()` instead.

**Comment by stephenh** [comment]
Ah, sure, agreed on .findAny(). Thanks for the really quick response!
