### ISSUE TITLE
Add Seq.toList(Supplier) and Seq.toSet(Supplier)

### ISSUE THREAD

**Issue by stephenh** [jOOQ/jOOL#95]
Not sure how you'll feel about this one, but currently in our app we often have to (due to serialization concerns) convert Streams/Seqs to concrete ArrayLists instead of just Lists.

Having Seq.toList() is great, but to get an ArrayList (in a way that appeases the type system; technically .toList() is making an ArrayList behind the scenes, but only as an implementation detail), we still need:

```
.collect(toCollection(ArrayList::new))))
```

So being able to do Seq.toArrayList would be really great.

I understand this could be a slippery slope, in terms of a whole bunch of "to<ConcreteType>()" methods not scaling very well.

My rationale is that ArrayList is a very common/built-in type ... and we need it, so that biases my logic. :-)

Dunno, maybe something like Seq.to(ArrayList::new) would be possible? 

This would be like the Scala collections API, which has:

```
Seq(1, 2, 3).to[Vector]
```

Where the type parameter Vector lets users request their own concrete implementation in a fairly succinct manner.

Obviously Scala is using manifests to instantiate the new collection just based on the type parameter, so we can't do exactly that. But Seq.to(ArrayList::new), assuming the type sigs/etc. work out, might be a nice compromise.

This is more of a wish list item, so feel free to close if you think it's not a good addition.

**Comment by lukaseder** [comment]
How do you feel about the existing `Seq.toCollection(Supplier)`? Given that we also have `toMap()`, `toString()`, and possibly also other `toXYZ()` methods in the future, I don't like the idea of tying the semantics of `to()` to lists / collections only...

**Comment by stephenh** [comment]
Hm. Good point about toMap/toString.

Nice, I had missed .toCollection.

I probably would have found it if there was a .toList(Supplier) overload. Which is also just a tiny bit shorter. :-)

I don't think a .toList(Supplier) overload would hurt, but up to you if you think its too redundant.

**Comment by lukaseder** [comment]
I can live with `toList()` and `toSet()` as those already exist (without any arguments). So, let's overload!

**Comment by lukaseder** [comment]
N.B: We'll wait 1-2 weeks for more good ideas from you, and then we might just as well be ready to cut a release with the new features...

**Comment by stephenh** [comment]
Sounds great, thanks!
