### ISSUE TITLE
Add Seq.sortBy

### ISSUE THREAD

**Issue by stephenh** [jOOQ/jOOL#96]
Currently sorting objects by an attribute can be done by, e.g. sorting by name:

```
   Seq(o1, o2).sorted((o1, o2) -> o1.getName().compareTo(o2.getName()))
```

Scala has a nice `sortBy` function that avoids calling .getName twice:

```
   Seq(o1, o2).sortBy(o -> o.getName());
```

Where the lambda returns a Comparable, so the .sortBy can do the .compareTo as needed.

**Comment by lukaseder** [comment]
I guess the standard way to sort by a function in Java 8 is to use:

```java
seq(o1, o2).sorted(Comparator.comparing(o -> o.getName()))
```

I agree though, that a shortcut for the above as you suggested would be rather useful. I'll pull, but rename the method to the expected `sorted()`, to lessen the surprise for someone discovering the API

**Comment by stephenh** [comment]
Thanks! You're right that it's just a short cut.

FWIW Scala's Seq has Seq.sorted and Seq.sortBy as different method names, and I kind of like how the "sort by (function)" reads in my head, but sorted is perfectly fine too. I'll get used to it. :-)

**Comment by lukaseder** [comment]
Well, same story as over here: https://github.com/jOOQ/jOOL/issues/93#issuecomment-122901666. Besides (being a SQL person), the only reasonable reading would be `ORDER BY` anyway... ;)

**Comment by stephenh** [comment]
> the only reasonable reading would be ORDER BY anyway... ;)

Of course. :-)
